import { Router, type IRouter } from "express";
import { db, villagesTable, tourismTable, usersTable } from "@workspace/db";
import bcrypt from "bcryptjs";
import { eq, count } from "drizzle-orm";

const router: IRouter = Router();

const VILLAGES = [
  { name: "Thibella", nameST: "Thibella", description: "A vibrant residential community within Stadium Area, known for its strong community bonds and active neighbourhood associations.", descriptionST: "Sechaba sa bodulo se phelang ka hare ho Sebaka sa Setadieme, se tsebahetseng ka mebaneng ea sona e tiileng le mekhatlo e sebetsang ea motse." },
  { name: "Lower Thamae", nameST: "Thamae e Tlase", description: "A historic village forming part of the greater Thamae community. Home to established families and a hub of daily commerce and social life.", descriptionST: "Motse oa nalane o etsang karolo ea sechaba se seholo sa Thamae. Lehae la malapa a tiileng le seetsa sa khoebo ea letsatsi le letsatsi." },
  { name: "Moshoeshoe II", nameST: "Moshoeshoe II", description: "Named in honour of King Moshoeshoe II, this neighbourhood is a proud testament to Basotho royal heritage and modern urban living.", descriptionST: "E reilwe lebitso ka tlotliso ea Morena Moshoeshoe II, motse ono ke bopaki bo motlotlo ba fanaue ea bogosi ba Basotho le bophelo ba motse oa mehleng ena." },
  { name: "Sea Point", nameST: "Sea Point", description: "One of the most recognisable neighbourhoods in Stadium Area, Sea Point is a lively community close to Setsoto Stadium with a thriving local economy.", descriptionST: "E le e 'ngoe ea metse e tsebahetseng ka ho fetisisa ho Sebaka sa Setadieme, Sea Point ke sechaba se phelang haufi le Setsoto." },
  { name: "Marallaneng", nameST: "Marallaneng", description: "A growing residential area characterised by strong family values, access to local amenities, and a reputation for community solidarity.", descriptionST: "Sebaka sa bodulo se holang se khethuoa ke boleng bo tiileng ba lelapa, phihlelo ea lintlha tsa sechaba." },
  { name: "Phahameng", nameST: "Phahameng", description: "Elevated in both location and aspiration, Phahameng is a proud and ambitious village within the constituency striving for progress and development.", descriptionST: "E phahameng ho fapana le sebaka le morero, Phahameng ke motse o motlotlo le o nang le meharo ka hare ho sebaka sa botokomelo." },
  { name: "Maseru East", nameST: "Maseru Bochabela", description: "A densely populated and economically active zone forming the eastern boundary of Stadium Area, connecting the constituency to the wider Maseru urban fabric.", descriptionST: "Sebaka se koahlileng ka batho le se sebetsang ka moruo se etsang moeli oa bochabela oa Sebaka sa Setadieme." },
  { name: "Mohalalitoe", nameST: "Mohalalitoe", description: "A culturally rich village where traditions are maintained across generations. Mohalalitoe residents take great pride in their Basotho identity and communal spirit.", descriptionST: "Motse o ruileng ka setso moo mekhoa e bolokiloeng e tsoelang pele ho tsoa sehloohong ho sehloohong." },
  { name: "Pitso Ground", nameST: "Sebaka sa Pitso", description: "Named after the traditional Basotho gathering — the pitso — this neighbourhood honours the democratic tradition of open community consultation central to Basotho governance.", descriptionST: "E reilwe lebitso kamora kopano ea tloaelehileng ea Basotho — pitso — motse ono o hlompha mokopo oa tokoloho oa phuputso ea sechaba." },
  { name: "Upper Thamae", nameST: "Thamae e Holimo", description: "Home to the LECSA church, Sefika High School, and a tight-knit faith community. Upper Thamae is the spiritual and educational heart of Stadium Area's northern villages.", descriptionST: "Lehae la kereke ea LECSA, Sekolo se Phahameng sa Sefika, le sechaba sa tumelo se koahlileng. Thamae e Holimo ke pelo ea moya le thuto." },
  { name: "Cathedral Area", nameST: "Sebaka sa Kathedrale", description: "Adjacent to Our Lady of Victories Cathedral, this neighbourhood carries a deeply spiritual identity and serves as an important civic and religious landmark in Maseru.", descriptionST: "E haufi le Kathedrale ea Our Lady of Victories, motse ono o tshwara boitsebiso bo boholo ba moya." },
  { name: "Emmanuel Hostel", nameST: "Hosele ea Emmanuel", description: "Originally established as a residential hostel for workers, Emmanuel Hostel has evolved into a thriving community with a diverse and resilient population.", descriptionST: "E thehiloe pele e le hosele ya bohlokwa bakeng sa basebetsi, Emmanuel Hostel e fetohile sechaba se phelang le sechaba se fapaneng." },
  { name: "Fokothi", nameST: "Fokothi", description: "A characterful village within Stadium Area with deep roots in the Maseru urban landscape. Fokothi residents are known for their warmth and communal pride.", descriptionST: "Motse o nang le sebopeho ka hare ho Sebaka sa Setadieme o nang le metheo e tebileng ho lefatšeng la motse oa Maseru." },
  { name: "NTTC Area", nameST: "Sebaka sa NTTC", description: "Home to the National Teacher Training College (NTTC), this neighbourhood is an educational enclave that has shaped generations of Lesotho's teaching workforce.", descriptionST: "Lehae la Kolechana ea Naha ea Thupelo ea Matichere (NTTC), motse ono ke sebaka sa thuto se bopileng matichere a Lesotho." },
  { name: "Ntšerele", nameST: "Ntšerele", description: "A quiet residential neighbourhood forming part of the Lower Thamae cluster, Ntšerele maintains strong community ties and traditional neighbourhood values.", descriptionST: "Sebaka sa bodulo se khutsitseng se etsang karolo ea sehlopha sa Thamae e Tlase, Ntšerele e boloka mebaneng e tiileng." },
  { name: "Temong", nameST: "Temong", description: "A neighbourhood of significant character, Temong forms part of the cultural mosaic of Stadium Area with established families and community institutions.", descriptionST: "Motse oa boemo bo boholo, Temong oa etsang karolo ea setso sa Stadium Area ka malapa a tiileng le mekhatlo ea sechaba." },
  { name: "Thabong", nameST: "Thabong", description: "One of the established residential areas in Stadium Area. The name Thabong — 'place of joy' — reflects the community spirit that defines this neighbourhood.", descriptionST: "E le e 'ngoe ea libaka tsa bodulo tse tiileng ho Sebaka sa Setadieme. Lebitso Thabong — 'sebaka sa thabo' — le bontša moea oa sechaba." },
  { name: "Save the Children Area", nameST: "Sebaka sa Save the Children", description: "Named after the notable humanitarian presence in the area. This neighbourhood reflects the constituency's commitment to child welfare, education, and community support.", descriptionST: "E reilwe lebitso kamora boteng bo hlokehang ba botho-botle. Motse ono o bonts'a boikarabello ba sechaba ho ts'ireletso ea bana." },
];

const TOURISM = [
  { name: "Setsoto National Stadium", nameST: "Setadieme sa Naha sa Setsoto", category: "Sports & Entertainment", description: "Lesotho's premier national stadium with a current capacity of 20,000 (expanding to 25,000 in 2026). Home of the Lesotho national football team. Built 1992, the stadium hosts football, athletics, motorsport, concerts, and major national ceremonies including the 1997 coronation of King Letsie III.", descriptionST: "Setadieme sa naha sa Lesotho se ka sehloohong se nang le bokhoni ba hajoale ba 20,000 (bo holisoa ho 25,000 ka 2026). Lehae la sehlopha sa bolo ea maoto sa Lesotho.", address: "Stadium Area, Maseru, Lesotho", phone: "+266 2232 0000" },
  { name: "Our Lady of Victories Cathedral", nameST: "Kerekeng ea Our Lady of Victories", category: "Religious & Heritage", description: "A magnificent Roman Catholic Cathedral built in the colonial era, situated 1km southwest of Setsoto Stadium. One of the most architecturally significant religious buildings in Maseru, featuring stunning stone architecture and stained glass.", descriptionST: "Kathedrale e ntle ea Moromonyi oa Roma e hahiloeng mehleng ea bokolone, e leng 1km boroa-bophirima ba Setsoto.", address: "Cathedral Area, Maseru, Lesotho", phone: "+266 2232 2555" },
  { name: "Royal Palace of Lesotho", nameST: "Lekhotla la Morena oa Lesotho", category: "Heritage & Royalty", description: "The official residence of His Majesty the King of Lesotho, located near Stadium Area. While the interior is restricted, the palace grounds and exterior are a must-see landmark representing Basotho royal heritage and national identity.", descriptionST: "Lehae la semmuso la Morena oa Lesotho, e leng haufi le Stadium Area. Ntle le sephiri sa ka hare, libaka tsa lekhotla le ka ntle ke sebaka se hlokehang.", address: "Kingsway, Maseru, Lesotho", phone: "+266 2231 4000" },
  { name: "National Museum of Lesotho", nameST: "Musiamo oa Naha oa Lesotho", category: "Culture & History", description: "Lesotho's national museum preserving and celebrating the rich cultural heritage of the Basotho people. Exhibitions include traditional artefacts, San rock art, historical photographs, traditional attire including the iconic mokorotlo hat, and Basotho blankets.", descriptionST: "Musiamo oa naha oa Lesotho o bolokang le ho phehla fanaue e ruileng ea setso sa Basotho. Lipontšo li kenyelletsa lithepa tsa tloaelehang.", address: "Kingsway, Maseru, Lesotho", phone: "+266 2232 3768" },
  { name: "Pitso Ground Open Space", nameST: "Sebaka se Bulehileng sa Pitso Ground", category: "Community & Recreation", description: "The historic open ground named after the traditional Basotho pitso (community gathering). This space serves as a public square for community events, traditional celebrations, and open-air markets. A living symbol of Basotho democratic traditions.", descriptionST: "Lebala la nalane le reilweng lebitso kamora pitso ea tloaelehileng ea Basotho. Sebaka sena se sebeletsana e le lebaleng la sechaba.", address: "Pitso Ground, Stadium Area, Maseru", phone: "" },
  { name: "Mohalalitoe Recreation Park", nameST: "Pareke ea Mohalalitoe", category: "Parks & Recreation", description: "A community park and recreational space within the Mohalalitoe village area. Popular with families, children, and sports enthusiasts. Features football pitches, open lawns, and community gathering areas used for local tournaments and events.", descriptionST: "Pareke ea sechaba le sebaka sa ho ipapalla ka hare ho sebaka sa motse oa Mohalalitoe. E ratehile ho malapa, bana, le baphaphathehi ba papali.", address: "Mohalalitoe, Stadium Area, Maseru", phone: "" },
  { name: "Lerotholi Polytechnic Open Day", nameST: "Letsatsi la Politekniki ea Lerotholi", category: "Education & Innovation", description: "Lerotholi Polytechnic regularly opens its workshops, engineering labs, and design studios to visitors. Students showcase robotics, construction projects, fashion design, and technical innovation. An inspiring destination for families and young people.", descriptionST: "Politekniki ea Lerotholi e bula ka hoLerotholi ho baeti basebetsaneng ba yona, lilaaboratori tsa injiniere, le lisutudio tsa moralo.", address: "Moshoeshoe Road, Stadium Area, Maseru", phone: "+266 2232 4066" },
  { name: "Maseru Craft Market (Stadium Area)", nameST: "Mmaraka oa Mekhoa ea Maseru", category: "Shopping & Culture", description: "A vibrant craft and trade market near Stadium Area where local artisans sell handwoven Basotho blankets, mokorotlo hats, pottery, beadwork, woodcarving, and traditional foods. A must-visit for authentic souvenirs and cultural experiences.", descriptionST: "Mmaraka o phelang oa mekhoa le khoebo haufi le Stadium Area moo baetsi ba mahae ba rekisang makota a Basotho, likatiba tsa mokorotlo.", address: "Stadium Area Market Square, Maseru", phone: "+266 5880 0000" },
  { name: "Sefika High School Cultural Grounds", nameST: "Sebaka sa Setso sa Sefika", category: "Education & Culture", description: "During Bochaba Day and cultural events, the Sefika High School grounds transform into a spectacular celebration of Basotho heritage — traditional dances, music, attire, and food. Open to community visitors during scheduled cultural days.", descriptionST: "Ka Letsatsi la Bochaba le liketsahalo tsa setso, libaka tsa Sekolo se Phahameng sa Sefika li fetoha phehlo e makatsang ea fanaue ea Basotho.", address: "Upper Thamae, Stadium Area, Maseru", phone: "+266 2232 1234" },
  { name: "Thamae River Walk", nameST: "Ho Tsamaea Molapo oa Thamae", category: "Nature & Recreation", description: "A scenic riverside walking path along the Thamae area, offering beautiful views of the surrounding mountains and valleys. Popular with morning joggers, families, and nature lovers. Connects several villages within the constituency.", descriptionST: "Tsela e ntle ea ho tsamaea ka thoko ea molapo mabakeng a Thamae, e fana ka maikutlo a mabotse a lithaba le meqo e potapotileng.", address: "Lower Thamae, Stadium Area, Maseru", phone: "" },
  { name: "Upper Thamae LECSA Church Heritage Site", nameST: "Sebaka sa Nalane sa LECSA ea Thamae e Holimo", category: "Religious & Heritage", description: "The LECSA congregation at Upper Thamae has served the community since the 19th century. The church building, its gardens, and surrounding community spaces represent a living heritage site of Basotho Christian identity and community life.", descriptionST: "Phuthehano ea LECSA e Thamae e Holimo e sebeleletse sechaba ho tloha lekholong la bo19. Kaho ea kereke, mapolasi a yona.", address: "Upper Thamae, Stadium Area, Maseru", phone: "+266 5890 1234" },
  { name: "Sea Point Community Sports Hub", nameST: "Setsi sa Lipapali sa Sechaba sa Sea Point", category: "Sports & Recreation", description: "Sea Point is home to several informal football pitches and community sports grounds. Weekend matches draw passionate local crowds, reflecting the deep love of football across Stadium Area. Multi-purpose grounds also host athletics and community events.", descriptionST: "Sea Point ke lehae la mabala a mangata a bolo ea maoto a sa semmuso le mabala a papali ea sechaba.", address: "Sea Point, Stadium Area, Maseru", phone: "" },
  { name: "Maseru East Market", nameST: "Mmaraka oa Maseru Bochabela", category: "Shopping & Commerce", description: "A bustling local market in Maseru East serving the eastern communities of Stadium Area constituency. Fresh produce, street food, clothing, electronics, and household goods are available. A true hub of everyday community commerce and social interaction.", descriptionST: "Mmaraka oa sechaba o phelang Maseru Bochabela o sebeletsang sechaba sa bochabela sa Stadium Area. Lithepa tse tala, lijo tsa seterata.", address: "Maseru East, Stadium Area, Maseru", phone: "" },
  { name: "Lesotho High School Campus Walk", nameST: "Ho Tsamaea Kepe ea Sekolo se Phahameng sa Lesotho", category: "Education & Heritage", description: "Lesotho High School — one of the country's most prestigious secondary institutions — welcomes visitors interested in its historic campus, sports facilities, and academic heritage. Arranged visits can be made through the school office.", descriptionST: "Sekolo se Phahameng sa Lesotho — e le e 'ngoe ea lithuto tse phahameng ka ho fetisisa tsa naha — se amohela baeti ba nang le khahliso ea kepe ea yona ea nalane.", address: "Lesotho High School Area, Stadium Area, Maseru", phone: "+266 2232 1100" },
  { name: "Moshoeshoe II Village Cultural Trail", nameST: "Tsela ea Setso ea Motse oa Moshoeshoe II", category: "Culture & Heritage", description: "A self-guided heritage walk through Moshoeshoe II village, one of Stadium Area's most historically significant neighbourhoods. Named after King Moshoeshoe II, the village features murals, traditional house styles, and community cultural markers.", descriptionST: "Leeto la fanaue la ho itataisa le tsamaeang ho pota motse oa Moshoeshoe II, e le e 'ngoe ea metse ea nalane ka ho fetisisa ho Sebaka sa Setadieme.", address: "Moshoeshoe II Village, Stadium Area, Maseru", phone: "" },
];

router.post("/seed", async (req, res): Promise<void> => {
  const key = req.body?.key;
  if (key !== "STADIUM-SEED-2025") {
    res.status(403).json({ error: "Invalid seed key" });
    return;
  }

  const [{ value: villageCount }] = await db.select({ value: count() }).from(villagesTable);
  if (Number(villageCount) === 0) {
    await db.insert(villagesTable).values(VILLAGES);
  }

  const [{ value: tourismCount }] = await db.select({ value: count() }).from(tourismTable);
  if (Number(tourismCount) === 0) {
    await db.insert(tourismTable).values(TOURISM);
  }

  const adminEmail = "admin@stadiumarea.ls";
  const [existingAdmin] = await db.select().from(usersTable).where(eq(usersTable.email, adminEmail));
  if (!existingAdmin) {
    const passwordHash = await bcrypt.hash("admin2025!", 10);
    await db.insert(usersTable).values({
      name: "Stadium Area Admin",
      email: adminEmail,
      whatsapp: "+26622320000",
      passwordHash,
      village: "Stadium Area",
      address: "Constituency No. 32, Maseru",
      role: "admin",
    });
  }

  res.json({ ok: true, message: "Seeded successfully" });
});

export default router;
